# Generated by Django 3.1.7 on 2022-01-06 03:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='one.school')),
                ('overallRating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('overallEarned', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('overallAvailable', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('growthRating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('growthEarned', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('growthAvailable', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('achievementRating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('achievementEarned', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('achievementAvailable', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='one.school')),
                ('schoolWebsite', models.CharField(blank=True, max_length=200, null=True)),
                ('schoolWebsiteShort', models.CharField(blank=True, max_length=200, null=True)),
                ('enrollment', models.IntegerField(blank=True, null=True)),
                ('freeReducedLunch', models.IntegerField(blank=True, null=True)),
                ('minorityStudents', models.IntegerField(blank=True, null=True)),
                ('englishLearners', models.IntegerField(blank=True, null=True)),
                ('disabilityStudents', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suggested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.school')),
                ('suggest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggest', to='one.school')),
            ],
        ),
    ]
