# Generated by Django 3.1.7 on 2022-01-06 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggested',
        ),
    ]
