# Generated by Django 3.1.7 on 2022-01-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='one.school')),
                ('overallRating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('overallEarned', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('overallAvailable', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('growthRating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('growthEarned', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('growthAvailable', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('achievementRating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('achievementEarned', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('achievementAvailable', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
        ),
    ]
