# Generated by Django 3.1.7 on 2022-01-05 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='one.school')),
                ('schoolWebsite', models.CharField(max_length=200)),
                ('schoolWebsiteShort', models.CharField(max_length=200)),
                ('enrollment', models.IntegerField(blank=True, null=True)),
                ('freeReducedLunch', models.IntegerField(blank=True, null=True)),
                ('minorityStudents', models.IntegerField(blank=True, null=True)),
                ('englishLearners', models.IntegerField(blank=True, null=True)),
                ('disabilityStudents', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
