# Generated by Django 3.1.7 on 2022-01-06 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_auto_20220106_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggested',
            name='address',
        ),
        migrations.RemoveField(
            model_name='suggested',
            name='name',
        ),
        migrations.RemoveField(
            model_name='suggested',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='suggested',
            name='slug',
        ),
        migrations.CreateModel(
            name='Nearby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nearby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby', to='one.school')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='one.school')),
            ],
        ),
    ]
