# Generated by Django 3.1.7 on 2022-01-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0006_school_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearby',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
